env:
  browser: true
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 8
rules:
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - 0
