image: node:13-buster-slim

stages:
    - test
    - build
    - publish

coverage:
    stage: test
    tags:
        - docker-executor
    script:
        - ./scripts/run-tests.sh
    artifacts:
        paths:
            - coverage

build:
    stage: test
    script:
        - apt-get update && apt-get install -y rpm
        - cd iapplx && npm ci && npm run build
    artifacts:
        name: mystique-$CI_BUILD_REF
        paths:
            - iapplx/dist
        expire_in: 1 month

create_docs:
  image: ${CONTAINTHEDOCS_IMAGE}
  stage: build
  allow_failure: true
  script:
    - make html
    - echo "Checking grammar and style"
    # Runs the grammar check on everything except the /docs/drafts directory
    - vale --glob='*.rst' .
    - echo "Checking links"
    - make linkcheck

  tags:
    - cm-official-docker-executor
  artifacts:
    expire_in: 1 week
    name: sphinx-docs_$CI_BUILD_REF
    paths:
      - docs/_build/html

pages:
    stage: publish
    environment:
        name: staging
        url: https://${CI_PROJECT_NAMESPACE}.${PAGES_DOMAIN}/${CI_PROJECT_NAME}/
    tags:
        - cm-official-docker-executor
    dependencies:
        - coverage
    script:
       - PUBLIC_DIR='./public'
       - PUBLIC_DOCS=${PUBLIC_DIR}/public-docs
       - COVERAGE_DOCS=${PUBLIC_DIR}/coverage-docs
       - mkdir -p ${COVERAGE_DOCS}
       - mkdir -p ${PUBLIC_DIR}
       - mkdir -p ${PUBLIC_DOCS}
       - cp docs/index.html ${PUBLIC_DIR}/index.html
       - cp -R docs/_build/html/* ${PUBLIC_DOCS}
       - cp -R coverage/* ${COVERAGE_DOCS}
    artifacts:
        paths:
            - public
    only:
        - develop
        - doc-setup
