image: node:8

stages:
    - test
    - publish

coverage:
    stage: test
    tags:
        - docker-executor
    script:
        - cd core && npm ci && npm run lint && npm run coverage
        - cd ../iapplx && npm ci && npm run lint && npm run coverage
        - cd .. && npm install -g nyc
        - mkdir .nyc_output
        - cp -r core/.nyc_output/* .nyc_output
        - cp -r iapplx/.nyc_output/* .nyc_output
        - npx nyc report -r html
    artifacts:
        paths:
            - coverage

build:
    stage: test
    image: f5devcentral/containthedocs:rpmbuild
    script:
        - npm install --global npm@5.10.0
        - cd iapplx && npm run build
    artifacts:
        name: mystique-$CI_BUILD_REF
        paths:
            - iapplx/dist
        expire_in: 1 month

pages:
    stage: publish
    environment:
        name: staging
        url: https://${CI_PROJECT_NAMESPACE}.${PAGES_DOMAIN}/${CI_PROJECT_NAME}/
    tags:
        - cm-official-docker-executor
    dependencies:
        - coverage
    script:
       - PUBLIC_DIR='./public'
       - COVERAGE_DOCS=${PUBLIC_DIR}/coverage-docs
       - mkdir -p ${COVERAGE_DOCS}
       - cp -R coverage/* ${COVERAGE_DOCS}
    artifacts:
        paths:
            - public
    only:
        - develop
