image: node:8

stages:
    - test
    - build

test:
    image: node:8
    stage: test
    tags:
        - docker-executor
    script:
        - npm run install-test
        - npm run lint
    artifacts:
        name: ${CI_COMMIT_REF_NAME}_test_artifacts
        paths:
            - test/artifacts
        when: on_failure
        expire_in: 3 days

build:
    image: f5devcentral/containthedocs:rpmbuild
    stage: build
    script:
        - npm run install-production
        - npm run build
    artifacts:
        name: mystique-$CI_BUILD_REF
        paths:
            - dist
        expire_in: 1 month
