image: node:13-buster-slim

stages:
    - test
    - publish

coverage:
    stage: test
    tags:
        - docker-executor
    script:
        - ./scripts/run-tests.sh
    artifacts:
        paths:
            - coverage

build:
    stage: test
    script:
        - apt-get update && apt-get install -y rpm
        - cd iapplx && npm ci && npm run build
    artifacts:
        name: mystique-$CI_BUILD_REF
        paths:
            - iapplx/dist
        expire_in: 1 month

pages:
    stage: publish
    environment:
        name: staging
        url: https://${CI_PROJECT_NAMESPACE}.${PAGES_DOMAIN}/${CI_PROJECT_NAME}/
    tags:
        - cm-official-docker-executor
    dependencies:
        - coverage
    script:
       - PUBLIC_DIR='./public'
       - COVERAGE_DOCS=${PUBLIC_DIR}/coverage-docs
       - mkdir -p ${COVERAGE_DOCS}
       - cp -R coverage/* ${COVERAGE_DOCS}
    artifacts:
        paths:
            - public
    only:
        - develop
